version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: db-hospital
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: luislindo
      MYSQL_DATABASE:
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - .database/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the SQL file as an initialization script

  java_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: jdbc:mysql://mysql:3307/your_database_name
      JDBC_USER: root
      JDBC_PASSWORD: luislindo

volumes:
  mysql_data:
