-- Active: 1710536052513@@127.0.0.1@3306@HOSPITAL
DROP DATABASE IF EXISTS HOSPITAL;

CREATE DATABASE HOSPITAL;

USE HOSPITAL;

CREATE TABLE
  ADDRES (
    PUBLIC_AREA VARCHAR(20),
    DISTRICT VARCHAR(30),
    NUM INT,
    CEP INT,
    PRIMARY KEY (CEP, NUM)
  );

CREATE TABLE
  PERSON (
    PERSON_ID INT AUTO_INCREMENT,
    NAM VARCHAR(40),
    BIRTH VARCHAR(11),
    ADDRES_NUM INT,
    ADDRES_CEP INT,
    PERSON_TYPE ENUM ('DOCTOR', 'PACIENT', 'BOOTH'),
    PRIMARY KEY (PERSON_ID),
    FOREIGN KEY (ADDRES_CEP, ADDRES_NUM) REFERENCES ADDRES (CEP, NUM) ON UPDATE CASCADE ON DELETE CASCADE
  );

CREATE TABLE
  SPECIALITY (
    CRM INT NOT NULL,
    SPT1 VARCHAR(40),
    SPT2 VARCHAR(40),
    SPT3 VARCHAR(40),
    PRIMARY KEY (CRM)
  );

CREATE TABLE
  DOCTOR (
    PERSON_ID INT NOT NULL,
    CRM INT,
    PAYMENT FLOAT,
    PRIMARY KEY (CRM),
    Foreign Key (CRM) REFERENCES SPECIALITY (CRM) ON UPDATE CASCADE ON DELETE CASCADE,
    Foreign Key (PERSON_ID) REFERENCES PERSON (PERSON_ID) ON UPDATE CASCADE ON DELETE CASCADE
  );

CREATE TABLE
  PACIENT (
    PERSON_ID INT NOT NULL,
    CPF CHAR(14),
    PRIMARY KEY (CPF),
    Foreign Key (PERSON_ID) REFERENCES PERSON (PERSON_ID) ON UPDATE RESTRICT ON DELETE CASCADE
  );

CREATE TABLE
  INSURANCE (
    PACIENT_ID CHAR(14),
    ISRC_NAME VARCHAR(63),
    PAYMENT FLOAT,
    PRIMARY KEY (PACIENT_ID),
    FOREIGN Key (PACIENT_ID) REFERENCES PACIENT (CPF) ON UPDATE RESTRICT ON DELETE CASCADE
  );

CREATE TABLE
  APPOINTMENT (
    PACIENT_ID CHAR(15),
    DOCTOR_ID INT,
    APPOINTMENT_DATE VARCHAR(10),
    PRIMARY KEY (PACIENT_ID, DOCTOR_ID),
    Foreign Key (PACIENT_ID) REFERENCES PACIENT (CPF) ON UPDATE RESTRICT ON DELETE RESTRICT,
    Foreign Key (DOCTOR_ID) REFERENCES DOCTOR (CRM) ON UPDATE RESTRICT ON DELETE RESTRICT
  );

CREATE TABLE
  HOSPITAL_PROCEDURE (
    PACIENT_ID CHAR(15),
    DOCTOR_ID INT,
    PROCEDURE_DATE VARCHAR(10),
    PRICE FLOAT,
    DURATION FLOAT,
    ROOM VARCHAR(40),
    PROCEDURE_TYPE ENUM ('FARINGOPLASTIA', 'NEUROCIRURGIA'),
    PRIMARY KEY (PACIENT_ID, DOCTOR_ID),
    Foreign Key (PACIENT_ID) REFERENCES PACIENT (CPF) ON UPDATE RESTRICT ON DELETE RESTRICT,
    Foreign Key (DOCTOR_ID) REFERENCES DOCTOR (CRM) ON UPDATE RESTRICT ON DELETE RESTRICT
  );